### ISSUE TITLE
上传大文件出现错误

### ISSUE THREAD

**Issue by sayiwen** [zgldh/qiniu-laravel-storage#10]
我是直接集成到October CSM 的。"Allowed memory size of 120586240 bytes exhausted (tried to allocate 99775249 bytes)"

**Comment by zgldh** [comment]
希望把全部错误日志贴出来。这样能定位到具体哪一行错误

**Comment by sayiwen** [comment]
```
php.ini:
upload_max_filesize = 400M
post_max_size = 400M

"Allowed memory size of 120586240 bytes exhausted (tried to allocate 99775249 bytes)" on line 52 of /home/wwwroot/lnmp/domain/*****/web/vendor/qiniu/php-sdk/src/Qiniu/Http/Client.php
```
内存够的

**Comment by zgldh** [comment]
你设定的是上传限制，不是PHP内存使用量。
请设置 
; Maximum amount of memory a script may consume (128MB)
; http://php.net/memory-limit
memory_limit = 128M 改成更高的数值。

另外代码已更新，请使用
    $disk->put('file.jpg',fopen('path/to/big.jpg','r+')); //分段上传文件。建议大文件>10Mb使用。
