### ISSUE TITLE
上传文件报错 local.ERROR: Qiniu: no such file or directory

### ISSUE THREAD

**Issue by liyu001989** [zgldh/qiniu-laravel-storage#13]
上传的时候文件不存在会报这个错，这是七牛的问题？

https://github.com/itbdw/laravel-storage-qiniu/blob/master/src/QiniuAdapter.php#L83

这个人把 612 过滤掉了。这么解决对吗

**Comment by zgldh** [comment]
不可能吧。正因为不存在所以才上传啊。你把程序上下文，调用栈，错误信息贴出来看看。

**Comment by liyu001989** [comment]
就这么点
$filename = 'foobar.jpg';
$file = \Storage::disk('public')->get($filename);
\Storage::disk('qiniu')->put($filename, $file);

报错
[2016-06-16 08:01:43] local.ERROR: Qiniu: no such file or directory.

传是传上去了，就是有个报错，你看上面链接里面那个人把612报错过滤了就说明不是我一个人出现这个问题吧

**Comment by zgldh** [comment]
为何要先 get ？

**Comment by liyu001989** [comment]
$disk->put('file.jpg',$contents);               //上传文件

难道contents是个路径？get出来另一个目录里面的问价内容啊

**Comment by zgldh** [comment]
哦看岔了 两个disk不一样

**Comment by zgldh** [comment]
我花点时间看看到底哪儿的事儿吧。

**Comment by liyu001989** [comment]
ok 
我问个问题啊，上传了一个图片，怎么获取图片地址

1，用下面两个方法吗？
$disk->getDriver()->imagePreviewUrl('file.jpg','imageView2/0/w/100/h/200'); //获取图片预览URL
$disk->getDriver()->privateImagePreviewUrl('file.jpg','imageView2/0/w/100/h/200');

七牛的实现，$url = "http://$this->domain/$key?$fops";  如果不传第二个参数会多个问号，自己trim掉吗

2. 难道是自己拼接？echo 'http://'.config('filesystems.disks.qiniu.domains.https').'/'.$filename;

**Comment by zgldh** [comment]
其实这个自己拼接就行。 imagePreviewUrl 纯粹没什么意义。
由于其图片格式化参数过于复杂，就不提供高级接口了。
建议在你的Image模型里写上类似于 getPreviewImageUrlAttribute 的方法来方便得到URL。

**Comment by liyu001989** [comment]
ok   thank you

**Comment by zgldh** [comment]
找到问题所在了。 laravel的文件系统在执行 put 时， 总会先执行 has 来检测是否存在该文件。调用来调用去，最后调用到了 QiniuAdapter 的 getMetaData 。 由于文件还没上传，该函数必定返回 612 错误。
于是我将该函数的错误日志的代码删掉了。问题解决了。

**Comment by liyu001989** [comment]
谢谢，怎么更新packagist啊，我composer更新一下

**Comment by hufeng903** [comment]
这个问题还是存在？

**Comment by zgldh** [comment]
我检查了我网站线上日志。没有发现类似问题。
如果你遇到了请新开一个issue贴出日志和代码上下文。
