### ISSUE TITLE
listContents 失能

### ISSUE THREAD

**Issue by zhylninc** [zgldh/qiniu-laravel-storage#16]
$disk->getDriver()->listContents("2014")
listContents方法传入 201404

service\vendor\league\flysystem\src\Util\ContentListingFormatter.php:108:

 return Util::dirname($entry['path']) === $this->directory;

Util::dirname($entry['path']) 为 “20140424/xxxxxx”
$this->directory为                   "201404"

因为不相等导致此方法不会返回任何数据

**Comment by zhylninc** [comment]
$disk->getDriver()->getAdapter()->listContents("2014")
可以返回七牛原有sdk内容

**Comment by zgldh** [comment]
文件库中有 20140102.jpg, 20140103.jpg 20150303.jpg
你希望 $disk->files('2014') 能得到 20140102.jpg, 20140103.jpg 两个文件对么？
