### ISSUE TITLE
put的时候，使用自动生成key

### ISSUE THREAD

**Issue by Cong5** [zgldh/qiniu-laravel-storage#19]
put的时候，能否使用qetag 自动生成key，七牛的去重好像使用的是这个

**Comment by zgldh** [comment]
我研究一下。。。还不懂什么qetag

**Comment by Cong5** [comment]
@zgldh etag的算法七牛已经开源出来的，可以参考： https://github.com/qiniu/qetag

**Comment by zgldh** [comment]
1. put方法我觉得还是要兼容`league/flysystem`的。返回值也要兼容。
2. 我打算提供一个函数，返回最后一次put的qetag的值。
这样应该也能满足要求

**Comment by zgldh** [comment]
0.6版 添加了 qetag 方法来得到最后一次 put 的hash值

**Comment by Cong5** [comment]
good,这个也不愧是一个很好的折中方案。
