### ISSUE TITLE
这个插件不支持php7.0么？

### ISSUE THREAD

**Issue by ChenPHPER** [zgldh/qiniu-laravel-storage#21]
![image](https://cloud.githubusercontent.com/assets/19897885/20374396/49781c5c-acb3-11e6-8897-353f8fc0b522.png)
我已经安装了扩展包了，但是还是有这个问题

**Comment by zgldh** [comment]
支持啊。我用的就是php7

**Comment by ChenPHPER** [comment]
解决了。我少装了一个扩展包
