### ISSUE TITLE
Undefined index: hash

### ISSUE THREAD

**Issue by zhouribin** [zgldh/qiniu-laravel-storage#22]
Qiniu Adapter line 242: Undefined index: hash  请问这是什么情况？文件已经到了qiniu上面 可是上传是报了这个错

**Comment by zgldh** [comment]
奇怪。。难道七牛改接口了么。 thanks milkmeowo 暂时去掉了这段代码。

**Comment by milkmeowo** [comment]
@zgldh 七牛没有改接口。可能是你没注意到，`qiniuPutFile`中没有解构七牛的返回就想直接取hash赋值了，所以报错，应该放在`writeStream`中解构之后取hash再赋值给`$this->lastQetag`。

**Comment by zgldh** [comment]
@milkmeowo  了解了，多谢！
