### ISSUE TITLE
上传文件,laravel日志中有Qiniu: no such file or directory错误日志

### ISSUE THREAD

**Issue by hufeng903** [zgldh/qiniu-laravel-storage#28]
错误日志：[2017-02-14 13:49:08] production.ERROR: Qiniu: no such file or directory 。
操作代码就是基本的put把一个本地文件，移动到七牛上。

**Comment by hufeng903** [comment]
可能和之前是一样的原因 Laravel 的文件系统在执行 put 时， 总会先执行 has 来检测是否存在该文件。我注释掉错误就不存在错误了

**Comment by zgldh** [comment]
你可以看看你使用的qiniu-laravel-storage库什么版本的，是否最新

**Comment by hufeng903** [comment]
我现在composer里面安装的"zgldh/qiniu-laravel-storage": "^0.3.0"这个版本？ 这个问题什么版本解决的？

**Comment by zgldh** [comment]
应该是0.4.2解决的

**Comment by hufeng903** [comment]
好的，谢谢
