### ISSUE TITLE
上传自动触发持久化方法

### ISSUE THREAD

**Issue by osindex** [zgldh/qiniu-laravel-storage#37]
$disk->put('file.jpg',$content, ['token'=>$uploadToken]); 
                                                    // 使用自定义的 uploadToken 进行上传。 
是不是无效？（私有空间操作，对视频加水印处理。）
有看到pull requests
不过 似乎没有更新到master。

--分支使用错误

**Comment by zgldh** [comment]
这个目前还有问题。。和  Laravel 的Filesystem用法有冲突。 put 第三个函数 Laravel 定义为 visibility， 不是config。
