### ISSUE TITLE
PHP7 lumen5.4使用这个包出现异常

### ISSUE THREAD

**Issue by jaekll** [zgldh/qiniu-laravel-storage#39]
QiniuFilesystemServiceProvider第28行\Storage 无法找到 以及 QiniuStorage 22行的\Storage
需要引入use Illuminate\Support\Facades\Storage;后去掉反斜杠才可用。

**Comment by zgldh** [comment]
这个啊。。一般来说Lumen要打开 facade 支持

> If you would like to use the DB facade, you should uncomment the $app->withFacades() call in your bootstrap/app.php file.

不过为了提高通用性，可以考虑你的改进方式。
