### ISSUE TITLE
https://packagist.org/ 上的0.8.2 版本还未更新上去呢？

### ISSUE THREAD

**Issue by xinuxZ** [zgldh/qiniu-laravel-storage#51]
https://packagist.org/packages/zgldh/qiniu-laravel-storage， 在用 persistentFop 发现0.8.1 的参数是错误的，0.8.2 虽修复，但是packagist.org最新还是0.8.1。什么时候更新上去呢？

**Comment by zgldh** [comment]
奇怪， packagist 应该是自动同步的。我看看

**Comment by zgldh** [comment]
@xinuxZ  0.8.2死活出不来， 我又怼了个 0.8.3。
