### ISSUE TITLE
安装之后使用有报错

### ISSUE THREAD

**Issue by huxiuhang** [zgldh/qiniu-laravel-storage#52]
报错信息如下：
 Symfony \ Component \ Debug \ Exception \ FatalThrowableError (E_ERROR)
Call to undefined function Qiniu\Http\curl_init()

ubuntu系统已经安装php-curl，并且已经在php.ini中打开了拓展，请问这个是什么问题

**Comment by zgldh** [comment]
别害羞，说出来让大家乐乐
