### ISSUE TITLE
persistentStatus($persistent_fop_id);  方法报错

### ISSUE THREAD

**Issue by huantu284** [zgldh/qiniu-laravel-storage#56]
如题，laravel版本5.5；

**Comment by zgldh** [comment]
方便把出错信息发来学习下么？

**Comment by huantu284** [comment]
![image](https://user-images.githubusercontent.com/6276264/36888079-e6fcffe0-1e2e-11e8-8932-a81a556061af.png)
就是qiniuAdapter里是静态调用的，改成非静态调用就好了。

**Comment by zgldh** [comment]
最新的 0.9.1 修复了这点。感谢您的反馈
