### ISSUE TITLE
由于七牛返回的时间单位是100纳秒，造成使用框架时和其他框架冲突引起时间转换问题

### ISSUE THREAD

**Issue by itfsw** [zgldh/qiniu-laravel-storage#58]
如果自己单独使用知道这个规则还好，但是很多其他框架整合时因为他们习惯按php逻辑来做就会导致时间错误。

**Comment by zgldh** [comment]
感谢提醒。我想想办法

**Comment by zgldh** [comment]
经过考虑，我认为本库不会解决这个问题。
如果我强行将其缩减为 Unix 时间戳，则会丢失了原始数据。不能反映 Qiniu 库的本来面目。
但这个地方我会在 ReadMe 里做出提醒。
