### ISSUE TITLE
  上传图片出现  ErrorException In Config.php line 44 :

### ISSUE THREAD

**Issue by megumi-i** [zgldh/qiniu-laravel-storage#63]
ErrorException In Config.php line 44 :
Trying to get property 'srcUpHosts' of non-object

public function getUpHost($accessKey, $bucket)
    {
        $zone = $this->getZone($accessKey, $bucket);
        if ($this->useHTTPS === true) {
            $scheme = "https://";
        } else {
            $scheme = "http://";
        }

        $host = $zone->srcUpHosts[0];
        if ($this->useCdnDomains === true) {
            $host = $zone->cdnUpHosts[0];
        }

        return $scheme . $host;
    }

查到是这句代码 出现了问题  是应为 ak 和 bucket 没传进去吗 

laravel 5.5

**Comment by zgldh** [comment]
看上去和他遇到的问题一样 #62 
但他并没有给出解决办法就关闭了，你可以联系他试试。

**Comment by megumi-i** [comment]
> 看上去和他遇到的问题一样 #62
> 但他并没有给出解决办法就关闭了，你可以联系他试试。

本地环境 一切正常 部署到服务器上 就 发生这个错误了

**Comment by zgldh** [comment]
你调用的是哪一个命令？ `$store->put('abc.jpg', $content); ` 这个么？
