### ISSUE TITLE
0.10.1 版本的bug：Type error: Too few arguments to function Qiniu\Storage\FormUploader::put()

### ISSUE THREAD

**Issue by echoldman** [zgldh/qiniu-laravel-storage#68]
Laravel 5.5 / php 7.1.29 / qiniu/php-sdk 7.2.8

会有以下错误信息：
Type error: Too few arguments to function Qiniu\Storage\FormUploader::put(), 7 passed in /Users/dongbin/Documents/Workspace/cyzy/customer-service/vendor/zgldh/qiniu-
  laravel-storage/src/QiniuAdapter.php on line 266 and exactly 8 expected

查看源码 FormUploader::put() 方法的第8个参数 $checkCrc 并没有使用，删除该参数或者设置默认值 null 或者调用传入 null 均可以正常使用。

**Comment by zgldh** [comment]
我检查一下。。

**Comment by zgldh** [comment]
七牛版本号管理太不严谨了。为put函数加参数，竟然只从 7.2.7 改成 7.2.8。 而且该参数没有卵用。
已经提了Issue https://github.com/qiniu/php-sdk/issues/304
我暂时发了新版本 0.10.2 锁定了 qiniu/php-sdk 到 7.2.7

**Comment by echoldman** [comment]
七牛也挺闹的。
