### ISSUE TITLE
图片删除时报错

### ISSUE THREAD

**Issue by chenjiajing** [zgldh/qiniu-laravel-storage#76]
![image](https://user-images.githubusercontent.com/16026990/99782712-7d0a3400-2b54-11eb-8a01-ba96a9521c92.png)
![image](https://user-images.githubusercontent.com/16026990/99782788-90b59a80-2b54-11eb-8144-e2f3f3b9e247.png)
如图，图片删除成功后返回  array (0 => NULL, 1 => NULL)， 每次删除都抛出异常，检查代码后发现，返回数据是数组而不是字符串，不知道是不是我自己的问题？麻烦帮忙看一下，谢谢。
环境： php 7.4.2 ,laravel 8.x

**Comment by chenjiajing** [comment]
@zgldh

**Comment by zgldh** [comment]
qiniu/php-sdk  版本多少呢？ 他们版本管控有些问题。
我建议你用 zgldh/qiniu-laravel-storage:v0.10.2 这样能锁定 qiniu/php-sdk:7.2.7 试试

**Comment by chenjiajing** [comment]
> qiniu/php-sdk 版本多少呢？ 他们版本管控有些问题。
> 我建议你用 zgldh/qiniu-laravel-storage:v0.10.2 这样能锁定 qiniu/php-sdk:7.2.7 试试

v0.10.2 可用，谢谢

**Comment by zgldh** [comment]
#77
