### ISSUE TITLE
delete 异常

### ISSUE THREAD

**Issue by shankesgk2** [zgldh/qiniu-laravel-storage#79]
PHP 7.4.7
laravel 6.18.15
qiniu/php-sdk 7.30
zgldh/qiniu-laravel-storage 0.10.3
delete('2.jpg')
Argument 1 passed to zgldh\\QiniuStorage\\QiniuAdapter::logQiniuError() must be an instance of Qiniu\\Http\\Error, array given, called in /xxxx/vendor/zgldh/qiniu-laravel-storage/src/QiniuAdapter.php on line 341

**Comment by shankesgk2** [comment]
已经更新到@Dev版本了

**Comment by zgldh** [comment]
#77
